name: config
version: 0.0.1
schema: v1

models:
  - name: MiniMax-M3
    provider: openai
    model: minimaxai/minimax-m3
    apiBase: https://integrate.api.nvidia.com/v1
    apiKey: $NVIDIA_API_KEY

tabAutocompleteModel:
  title: Tab Autocomplete
  provider: openai
  model: minimaxai/minimax-m3
  apiBase: https://integrate.api.nvidia.com/v1
  apiKey: $NVIDIA_API_KEY

contextProviders:
  - name: codebase
  - name: diff
  - name: terminal
  - name: folder
  - name: file
